// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveMyGame.src.Models;

#nullable disable

namespace SaveMyGame.Migrations
{
    [DbContext(typeof(ProgramDbContext))]
    partial class ProgramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("SaveMyGame.src.Models.ApplicationConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClearBeforeRestore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleteOldFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFastMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemindedSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsingLZMA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationConfigs");
                });

            modelBuilder.Entity("SaveMyGame.src.Models.FileRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestorePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
